name: CI

env:
  CI: false

on:
  push:
    branches: [ "main", "Extra-tools" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: |
        cd psyderella-frontend
        npm ci
        
    - name: Build the app
      run: |
        cd psyderella-frontend
        npm run build

    - name: Lint with EsLint
      run: |
        cd psyderella-frontend
        npm run lint

    - name: Run component tests
      run: |
        cd psyderella-frontend
        npm test

    - name: Start the app
      run:
        cd psyderella-frontend
        npm start &
        npx wait-on --timeout 6000

  build-backend:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: |
        cd psyderella-backend
        npm ci

      - name: Build the app
      run: |
        cd psyderella-backend
        npm run build --if-present
        
